Feature/cleanup scripts
architus/architus pull request #108
Opened 2020-07-03 20:10 UTC by AlexAppleManzer

## Description

Updated dbmanager to include cleanup scripts that are ran every time the container is started up. Also cleaned up johny's migration script and made a readme.

## Checklist

- [ ] [Linked PR to corresponding issue in this repo](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)
- [ ] Manually tested locally
- [ ] Additional issue created in [docs repo](https://github.com/architus/docs.archit.us/issues) (if necessary)

2020-07-07 03:44 UTC, jazeved0 requested changes

2020-07-07 03:44 UTC, jazevedo620 commented on dbmanager/dbmanager.py
> +    print(f"Running Cleanup Scripts: {list(map(os.path.basename, cleanup_scripts))}")
list comprehension is usually more readable

2020-07-07 03:44 UTC, jazevedo620 commented on dbmanager/dbmanager.py
> +    print('ok')
🤔

2020-07-07 03:44 UTC, jazevedo620 commented on dbmanager/dbmanager.py
> +    cleanup_scripts = get_all_files(CLEANUP_DIR, suffix=".sql")
Add doc comment >:(

2020-07-07 03:44 UTC, jazevedo620 commented on dbmanager/dbmanager.py
> +def run_scripts(file_paths):
Add doc comment >:(

2020-07-07 03:44 UTC, jazevedo620 commented on dbmanager/readme.md
> +# DB Manager
this file should be all caps `README.md` for consistency

2020-07-07 17:56 UTC, AlexAppleManzer commented on dbmanager/dbmanager.py
> +    print('ok')
:)

2020-07-07 19:37 UTC, jazeved0 approved these changes

2020-07-09 18:38 UTC, johnyburd commented on dbmanager/dbmanager.py
> +    """
you're allowed to do single lines like `"""comments here"""`

2020-07-11 21:58 UTC, johnyburd approved these changes

2020-07-21 03:02 UTC, merged